name: Build and Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    environment: production
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install --legacy-peer-deps

    - name: Build
      run: npm run build

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.AWS_IAM_ROLE }}
        aws-region: us-east-1
        role-duration-seconds: 1200

    - name: Sync to S3
      run: aws s3 sync . s3://barrancolab-blog
